### ISSUE TITLE
CSS files are too heavy

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-demo-app#5]
@priley86 patternfly.css is 1.3MB and the /dist folder is 9MB

There seems to be something wrong in the way we build things. If you get stuck with this you can contact @bleathem to bounce some ideas.

**Comment by andresgalante** [comment]
main.bundle.js and main.bundle.js.map are also super heavy

**Comment by priley86** [comment]
@andresgalante @bleathem right now it is concatenating all scripts in `src/js/main.js` into `dist/main.bundle.js`. If you add up all of the dependencies sizes, it should equal to that.

It is similar concept in the `patternfly.css`. All fonts and images are now inline. Maybe we can remove some fonts which are not being used from the bundle.

We can also reduce the size by removing some of the js deps that aren't used on this page, and creating separate entry points (see [multi-page-app](https://github.com/webpack/docs/wiki/optimization)). This would allow us to have separate bundles on different pages.

I'm up for any ideas. I think we should keep this issue open and consider.

**Comment by priley86** [comment]
I was doing some performance analysis on this app bundled with Webpack compared with the original source. 

Webpack bundled app:
https://rawgit.com/patternfly/patternfly-demo-app/master/dist/index.html
Original Source:
https://rawgit.com/priley86/patternfly-demo-app/old-code/index.html

While Webpack reduces the number of network requests, it seems the major difference is the time to load `patternfly.css`. The reason it is larger is Webpack is greedy in its optimizations and traces all fonts and images in the css and replaces them with inline data-uris/base64. With the number of fonts loaded, this adds up quickly.

To avoid this, I think we could use the `css-loader?-url` option in the Webpack [css-loader](https://github.com/webpack/css-loader). This should prevent url inlining behavior and reduce the size of the css. It looks like others had this issue before and requested this feature. See [#44](https://github.com/webpack/css-loader/issues/44).

From the js side, I think we are OK, as it is simply concatenating and minifying scripts, so the total bundle size should be equal to the original source. However, we could provide an example of splitting the bundle into pieces using [code splitting / multiple entry chunks](https://github.com/webpack/docs/wiki/optimization) for multi-page-app.

 @bleathem @dgutride @andresgalante - let me know if you guys agree. If so, will give this a shot.

**Comment by bleathem** [comment]
We should be aiming to keep this demo app as-simple-as-possible.  We don't want our community to get bogged down in the build/module details - there are plenty of online resources available to guide our users in this regard.

I would suggest we either:
1. Follow a well-defined usage pattern for incorporating webpack into this demo
2. Consider another tool that would offer a simpler demo.  Given that patternfly is not itself modular (yet), using webpack may be overkill.

**Comment by dtaylor113** [comment]
@bleathem +1 to keeping it simple.  I'm also concerned that the build process will overshadow the demo app.

**Comment by priley86** [comment]
@bleathem @dtaylor113 thanks for the feedback on this - I tend to agree. I attempted to follow best practices with Webpack, but I think this is just a facet of its optimization strategy. I think to keep things simple, I will attempt to prevent the url inlining in the css (to avoid this confusion and split out the fonts), and potentially split d3.js and c3.js into a separate bundle (that way it is an optional script include where needed). This should keep the file size down and provide clear examples of how to do this with Webpack.

I completely agree that Webpack is better suited for es6/module based apps which are a little more cutting edge, but it is still feasible as an optimization tool now. It will get consumers thinking about it as an option in the future and provide an example for them. 

Due to this, I propose we rename this repository "patternfly-demo-webpack" or something along those lines. This would open up the door for other demo apps and give it a clear separation.

Thoughts?

**Comment by dtaylor113** [comment]
+1 to "rename patternfly-demo-webpack"  -I think it's clearer and allows, perhaps, a more standard 'patternfly-demo' app.
